### ISSUE TITLE
v0.10.1 package is missing files referenced by exports

### ISSUE THREAD

**Issue by imjordanxd** [mcous/vitest-when#48]
## Summary

The npm package published as `vitest-when@0.10.1` does not contain the compiled files referenced by its package manifest:

- `dist/vitest-when.js`
- `dist/vitest-when.d.ts`

The package contains `src/vitest-when.ts`, but both the `exports` field and `types` field point to the missing `dist` files. As a result, consumers cannot resolve the package at runtime or during TypeScript compilation.

## Reproduction

1. Install `vitest-when@0.10.1` as a development dependency.
2. Import it from a test:

```ts
import { when } from 'vitest-when';
```

3. Run TypeScript or Vitest/Vite.

## Actual result

TypeScript reports:

```text
error TS2307: Cannot find module 'vitest-when' or its corresponding type declarations.
```

Vite/Vitest reports:

```text
Error: Failed to resolve import "vitest-when". Does the file exist?
```

Inspecting the installed package confirms that `package.json` and the TypeScript sources are present, but the exported `dist/vitest-when.js` and `dist/vitest-when.d.ts` files are absent.

## Expected result

The npm package should include the JavaScript and declaration files referenced by `exports` and `types`.

## Additional context

- `vitest-when@0.10.0` resolves and works correctly.
- Reproduced with Node.js 24, pnpm 11, TypeScript 7, Vite 8, and Vitest 4.
- This appears to be a publication artifact issue rather than a peer dependency or consumer configuration issue.

**Comment by mcous** [comment]
Thanks for the report, regression caused by #43. `v0.10.2` with the fix will be up shortly
